name: HD MADE
favicon: null
layout_spectrum: 1
typography_spectrum: 0.38002
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffe400'
    - '#535b63'
    - '#94999e'
    - '#c5c6c7'
  brandStrength: 1
  lightness: 0
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
