name: HD MADE
favicon: null
layout_spectrum: 0.8462
typography_spectrum: 0.44559
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#ffe400'
    - '#535b63'
    - '#94999e'
    - '#c5c6c7'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
